version: '3'
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  injest_data_fact_table:
    build:
      context: ./injest_data
      args:
        - user=root
        - password=root
        - host=pgdatabase
        - port=5432
        - db=ny_taxi
        - table_name=yellow_taxi_trips 
        - url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz
    depends_on:
      - pgdatabase
      - injest_data_zones
   

  injest_data_zones:
    build:
      context: ./injest_data
      args:
        - user=root
        - password=root
        - host=pgdatabase
        - port=5432
        - db=ny_taxi
        - table_name=zones
        - url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
    depends_on:
      - pgdatabase
